version: '3'
services:
  db:
    image: postgres:14.5-alpine
    container_name: db_url_service
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env

  url_service:
    build:
      context: ./src
    container_name: url_service
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    entrypoint: >
      sh -c "python utils/make_migration.py
      && uvicorn main:app --host 0.0.0.0 --port 8000"

volumes:
  db: