version: '3'
services:

  db:
    image: postgres:14.5-alpine
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "${DOCKER_DB_PORT}:5432"
    env_file:
      - .env
  
  url_service:
    build:
      context: ./src
    ports:
      - "${DOCKER_API_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - db
    entrypoint: >
      sh -c "sleep 5
      && alembic upgrade head
      && uvicorn main:app --host 0.0.0.0 --port 8000"
    
  tests:
    build:
      context: ./tests
    env_file:
      - .env
    depends_on:
      - url_service
    entrypoint: >
      sh -c "sleep 7
      && pytest"

volumes:
  db: