version: '3'
services:
  # create database special for tests
  test_db:
    image: postgres:14.5-alpine
    container_name: db
    volumes:
      - test_db:/var/lib/postgresql/data
    ports:
      - "${DOCKER_DB_PORT}:5432"
    env_file:
      - .env
  
  url_service:
    build:
      context: ./src
    ports:
      - "${DOCKER_API_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - test_db
    entrypoint: >
      sh -c "sleep 5
      && alembic upgrade head
      && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  tests:
    build:
      context: ./src
    env_file:
      - .env
    depends_on:
      - url_service
    entrypoint: >
      sh -c "sleep 7
      && pytest"

volumes:
  test_db: